site_name: relevanced
theme: yeti

docs_dir: docs
site_dir: build/site
pages:
- Introduction:
  - Welcome to relevanced: index.md
  - Motivations: introduction/motivations.md
  - Feature Overview: introduction/overview.md
- Examples:
  - Binary Classifier (Python): examples/python-binary-classifier.md
  - Multiclass Classifier (Python): examples/python-multiclass-classifier.md
  - Binary Classifier (Javascript): examples/javascript-binary-classifier.md
  - Binary Classifier (Scala): examples/scala-binary-classifier.md
  - Binary Classifier (Java): examples/java-binary-classifier.md
- Installation:
  - OS Packages: installation/os-packages.md
  - Docker Image: installation/docker.md
  - Configuration: installation/configuration.md
  - Building from Source: installation/building-from-source.md
- Commands: commands.md
- Clients:
  - Javascript: clients/javascript.md
  - Python: clients/python.md
  - Ruby: clients/ruby.md
  - Java: clients/java.md

